export * from "./create-game.interface"
export * from "./credential.interface"
export * from "./game.interface"
export * from "./make-move.interface"
export * from "./player.interface"
export * from "./request.interface"
export * from "./score.interface"
export * from "./user.interface"